language: cpp

dist: trusty
sudo: required
group: edge


compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-6
      - clang-5.0
      - libssl-dev

before_install:
  - sudo gem install asciidoctor
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-5.0" CC="clang-5.0"; fi

script:
  - echo $CC
  - echo $CXX
  - make

after_success:
  - ./ctguard-research --version
  - ./itests/run_all.sh
